"api-doc-entity-management"
ELEVATE-Project/entity-management pull request #19
Opened 2024-07-01 06:02 UTC by MallanagoudaB

2024-07-02 12:04 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/api-doc.yaml
> +                example1:
@MallanagoudaB SuccessResponse

2024-07-02 12:05 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/api-doc.yaml
> +                example1:
@MallanagoudaB FailureResponse

2024-07-04 06:38 UTC, MallanagoudaB commented on src/api-doc/api-doc.yaml
> +        `/v1/entities/mappingUpload`
no params we only require csv file in body

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs requested changes
Reviewed on jul-10

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/api-doc.yaml
> +        * The API Endpoint to read form data is `/v1/entityTypes/create/`
@MallanagoudaB Why there is / after create in URL?

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/api-doc.yaml
> +      summary: Update single entities based on the Id's
@MallanagoudaB based on what IDs?

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/api-doc.yaml
> +                    message: ENTITY_TYPES_FETCHED
@MallanagoudaB Why did you resolve this comment without actually resolving it?

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/api-doc.yaml
> +                        name: school
@MallanagoudaB change this to some other entity type name

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/api-doc.yaml
> +        You can use this API to entities data based on the type and ID we pass
@MallanagoudaB what id?

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/api-doc.yaml
> +      summary: Provide details of an entities based on entitie ID.
@MallanagoudaB spelling mistake

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/api-doc.yaml
> +          description: Please append a valid entitie id to the Request URL..
@MallanagoudaB remove one full stop

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/api-doc.yaml
> +          description: Please append a valid entities Id to the Request URL..
@MallanagoudaB remove extra full stop

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/api-doc.yaml
> +      summary: You can use this API to list entities based on its type
@MallanagoudaB make type to entity type

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/api-doc.yaml
> +        * The API Endpoint to get the realted entities data based on ID:
@MallanagoudaB still spelling issue why this comment was resolved?

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/api-doc.yaml
> +        You can use this API to get the realted entities data based on ID
@MallanagoudaB you resolved without correcting the spelling

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/api-doc.yaml
> +                Success Response:
@MallanagoudaB use same key every where

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity-Management-API's.json
> +			"name": "EntityType Service",
@MallanagoudaB why entityType service?

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity-Management-API's.json
> +							"raw": "http://localhost:5001/entity/v1/entityTypes/find",
@MallanagoudaB instead http://localhost:5001 give variable from environment eg: {{variable}}

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity-Management-API's.json
> +							"raw": "http://localhost:5001/entity/v1/entityTypes/create",
@MallanagoudaB instead http://localhost:5001 give variable from environment eg: {{variable}}

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity-Management-API's.json
> +							"raw": "http://localhost:5001/entity/v1/entityTypes/bulkUpdate",
@MallanagoudaB instead http://localhost:5001 give variable from environment eg: {{variable}}

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity-Management-API's.json
> +							"raw": "http://localhost:5001/entity/v1/entityTypes/list",
@MallanagoudaB instead http://localhost:5001 give variable from environment eg: {{variable}}

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity-Management-API's.json
> +								"value": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJuYW1lIjoiUHJpeWFua2EiLCJzZXNzaW9uX2lkIjoyMjcsIm9yZ2FuaXphdGlvbl9pZCI6MSwicm9sZXMiOlt7ImlkIjo3LCJ0aXRsZSI6Im9yZ19hZG1pbiIs
@MallanagoudaB do not append actual token.

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity-Management-API's.json
> +							"raw": "http://localhost:5001/entity/v1/entityTypes/bulkCreate",
@MallanagoudaB instead http://localhost:5001 give variable from environment eg: {{variable}}

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity-Management-API's.json
> +			"name": "Entities Service",
@MallanagoudaB why this is entities service? do we have service like that! make it entities

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity-Management-API's.json
> +							"raw": "http://localhost:5001/entity/v1/entities/listByEntityType/5f32d8228e0dc8312404056e?page=1",
@MallanagoudaB instead http://localhost:5001 give variable from environment eg: {{variable}}

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity-Management-API's.json
> +							"raw": "http://localhost:5001/entity/v1/entities/update/663364443c990eaa179e289e",
@MallanagoudaB instead http://localhost:5001 give variable from environment eg: {{variable}}

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity-Management-API's.json
> +							"raw": "http://localhost:5001/entity/v1/entities/bulkCreate?type=school",
@MallanagoudaB instead http://localhost:5001 give variable from environment eg: {{variable}}

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity-Management-API's.json
> +							"raw": "http://localhost:5001/entity/v1/entities/bulkUpdate",
@MallanagoudaB instead http://localhost:5001 give variable from environment eg: {{variable}}

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity-Management-API's.json
> +							"raw": "http://localhost:5001/entity/v1/entities/mappingUpload",
@MallanagoudaB instead http://localhost:5001 give variable from environment eg: {{variable}}

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity-Management-API's.json
> +							"raw": "http://localhost:5001/entity/v1/entities/list/5f33c3d85f637784791cd830?page=1&limit=100&type=school",
@MallanagoudaB instead http://localhost:5001 give variable from environment eg: {{variable}}

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity-Management-API's.json
> +							"raw": "http://localhost:5001/entity/v1/entities/relatedEntities/6153158e5bec1d28882358ab",
@MallanagoudaB instead http://localhost:5001 give variable from environment eg: {{variable}}

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity-Management-API's.json
> +							"raw": "http://localhost:5001/entity/v1/entities/find",
@MallanagoudaB instead http://localhost:5001 give variable from environment eg: {{variable}}

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity-Management-API's.json
> +							"raw": "http://localhost:5001/entity/v1/entities/details/663339bc0cb19f01c459853b",
@MallanagoudaB instead http://localhost:5001 give variable from environment eg: {{variable}}

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity-Management-API's.json
> +							"protocol": "http",
@MallanagoudaB instead http://localhost:5001 give variable from environment eg: {{variable}}

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity-Management-API's.json
> +							"raw": "http://localhost:5001/entity/v1/entities/add?type=state",
@MallanagoudaB instead http://localhost:5001 give variable from environment eg: {{variable}}

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity-Management-API's.json
> +							"raw": "http://localhost:5001/entity/v1/entities/subEntityListBasedOnRoleAndLocation/entity123",
@MallanagoudaB instead http://localhost:5001 give variable from environment eg: {{variable}}

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity-Management-API's.json
> +							"raw": "http://localhost:5001/entity/v1/entities/subEntityList/663354e56109810671aec49f?type=school&search=&page=1&limit=100",
@MallanagoudaB instead http://localhost:5001 give variable from environment eg: {{variable}}

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity-Management-API's.json
> +							"raw": "http://localhost:5001/entity/v1/entities/listByIds",
@MallanagoudaB instead http://localhost:5001 give variable from environment eg: {{variable}}

2024-07-10 03:31 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity-Management-API's.json
> +							"raw": "http://localhost:5001/entity/v1/entities/entityListBasedOnEntityType?entityType=state",
@MallanagoudaB instead http://localhost:5001 give variable from environment eg: {{variable}}

2024-07-12 10:20 UTC, VISHNUDAS-tunerlabs requested changes
reviewed on jul 12-2024 3:50 PM

2024-07-12 10:20 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity Management API's.postman_collection.json
> +		"name": "Entity Management API's",
@MallanagoudaB Lets keep it as Entity-Management

2024-07-12 10:20 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity Management API's.postman_collection.json
> +			"name": "entity",
@MallanagoudaB it is not entity it is entityType

2024-07-12 10:20 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity Management API's.postman_collection.json
> +							"raw": "{{baseUrl}}/entity/v1/entityTypes/find",
@MallanagoudaB {{baseUrl}}/entity/ will not work right it should be {{baseUrl}}/entity-management/
Please check all the urls in this postman collection. Very Important! not repeating same comment  again again

2024-07-12 10:20 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity Management API's.postman_collection.json
> +					"name": "Find",
@MallanagoudaB use same convention of endpoint , means make it "find". all lower case letters

2024-07-12 10:20 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity Management API's.postman_collection.json
> +					"name": "Update",
@MallanagoudaB all lowercase letters matching the endpoint

2024-07-12 10:20 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity Management API's.postman_collection.json
> +					"name": "Create",
@MallanagoudaB all lowercase letters matching the endpoint

2024-07-12 10:20 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity Management API's.postman_collection.json
> +					"name": "Update",
@MallanagoudaB all lowercase letters matching the endpoint

2024-07-12 10:20 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity Management API's.postman_collection.json
> +					"name": "BulkCreate",
@MallanagoudaB all lowercase letters matching the endpoint

2024-07-12 10:20 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity Management API's.postman_collection.json
> +					"name": "BulkUpdate",
@MallanagoudaB all lowercase letters matching the endpoint

2024-07-12 10:20 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity Management API's.postman_collection.json
> +					"name": "Details",
@MallanagoudaB all lowercase letters matching the endpoint

2024-07-12 10:20 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/Entity Management API's.postman_collection.json
> +					"name": "Add",
@MallanagoudaB all lowercase letters matching the endpoint

2024-07-12 10:54 UTC, MallanagoudaB commented on src/api-doc/api-doc.yaml
> +        You can use this API to list entity based on location id
no @VISHNUDAS-tunerlabs  only locationid both location and code have same value

2024-07-12 18:47 UTC, VISHNUDAS-tunerlabs requested changes
13-jul-2014 12:17 AM

2024-07-12 18:47 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/api-doc.yaml
> +          description: 'to update the data we need to match its id'
@MallanagoudaB bad description please add a proper one

2024-07-12 18:47 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/api-doc.yaml
> +          description: entity type of the entities we need to pass to match the entityType
@MallanagoudaB bad description :  
Please pass entity type value for the entity, 
check for similar changes

2024-07-12 18:47 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/api-doc.yaml
> +  /v1/entities/listByEntityType/{_id}?page={page_no}:
@MallanagoudaB  where is limit?

2024-07-12 18:47 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/api-doc.yaml
> +          description: Please appenda number for pagination.
@MallanagoudaB spelling mistake

2024-07-12 18:47 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/api-doc.yaml
> +      summary: 'bulkCreate create entityType '
@MallanagoudaB wrong summary. it should be Bulk create entity type

2024-07-15 04:58 UTC, MallanagoudaB commented on src/api-doc/api-doc.yaml
> +  /v1/entities/listByEntityType/{_id}?page={page_no}:
we dont have limit for this api

2024-07-17 07:12 UTC, VISHNUDAS-tunerlabs requested changes

2024-07-17 07:12 UTC, VISHNUDAS-tunerlabs commented on src/api-doc/api-doc.yaml
> +        * The API Endpoint tocreate a single entityType data is `/v1/entityTypes/create`
@MallanagoudaB space missing

2024-07-17 12:12 UTC, VISHNUDAS-tunerlabs approved these changes

2024-07-17 12:13 UTC, merged