"targetedRoles-api"
ELEVATE-Project/entity-management pull request #21
Opened 2024-07-19 14:22 UTC by MallanagoudaB

2024-07-22 06:15 UTC, VISHNUDAS-tunerlabs requested changes
Reviewed at jul 22 : 11:45

2024-07-22 06:15 UTC, VISHNUDAS-tunerlabs commented on src/module/entities/helper.js
> +					const userRolesResponse = await userService.userRole(userRoleFilter)
@MallanagoudaB do not make internal calls in loop. you should get all the entityType ids in an array. And pass that array to user service api call accordingly. and there using the array data make a query to fetch data

2024-07-22 06:15 UTC, VISHNUDAS-tunerlabs commented on src/generics/constants/common.js
> +	USER_LIST: '/v1/user-role/read',
@MallanagoudaB why this is in common.js it should be endpoints.js

2024-07-22 06:15 UTC, VISHNUDAS-tunerlabs commented on src/generics/services/user.js
> +			let url = userServiceUrl + CONSTANTS.common.USER_LIST
@MallanagoudaB The endpoint variable name is not suiting, you are not calling user_list api

2024-07-22 06:15 UTC, VISHNUDAS-tunerlabs commented on src/generics/constants/common.js
>  	FORM_SERVICE_URL: 'http://player:3000',
@MallanagoudaB is this endpoint used any where ? remove it if not used

2024-07-22 06:15 UTC, VISHNUDAS-tunerlabs commented on src/generics/services/user.js
> +const userServiceUrl = process.env.USER_SERVICE_URL
@MallanagoudaB Why this is not defied in envVariables.js and env samples files

2024-07-22 06:15 UTC, VISHNUDAS-tunerlabs commented on src/module/entities/helper.js
> +					results.data.push(...userRolesResponse.rows)
@MallanagoudaB all this logic has to be reworked. there should be a single user service call . Do not write api calls inside loops. You have to rework on user service api logic also.

2024-07-25 06:53 UTC, VISHNUDAS-tunerlabs requested changes
Finished second review at Jul 25 12:30

2024-07-25 06:53 UTC, VISHNUDAS-tunerlabs commented on src/module/entities/helper.js
> +				if (userRolesResponse.data.length < 0) {
@MallanagoudaB It will be better to add one more check for success=false, hence you are setting it for most of the error situations

2024-07-25 06:53 UTC, VISHNUDAS-tunerlabs commented on src/generics/constants/endpoints.js
> +	USER_READ: '/v1/user-role/read',
@MallanagoudaB this end point might change based on the review comments we added for user service

2024-07-25 07:04 UTC, VISHNUDAS-tunerlabs commented on src/controllers/v1/entities.js
> +	targetedRoles(req) {
@MallanagoudaB update api doc and postman collections, we are adding a new api

2024-07-26 12:13 UTC, VISHNUDAS-tunerlabs requested changes
reviewed 26 jul 5:43

2024-07-26 12:55 UTC, VISHNUDAS-tunerlabs commented on src/generics/services/user.js
> +			request.get(url, options, userReadCallback)
@MallanagoudaB should be post method.

2024-07-29 06:10 UTC, MallanagoudaB commented on src/module/entities/helper.js
> +				if (!fetchUserRoles.data || fetchUserRoles.data.length < 0) {
@VISHNUDAS-tunerlabs  im not getting success from that response so i added data from the last comment you added.

2024-07-29 09:55 UTC, VISHNUDAS-tunerlabs approved these changes
Reviewed 29 Jul 3:35 PM

2024-08-01 11:01 UTC, aks30 requested changes
Reviewed on 1 Aug

2024-08-01 11:01 UTC, aks30 commented on src/module/entities/helper.js
> +				const fetchUserRoles = await userServiceHelper.find(
@MallanagoudaB Why do we have to go to user service here, we have everything in mentoring only.

2024-08-01 11:06 UTC, MallanagoudaB commented on src/models/userRoleExtension.js
> +		userType: {
We have 2 types right 1 and 0 for admin

2024-08-01 11:15 UTC, MallanagoudaB commented on src/controllers/v1/userRoleExtension.js
> +	create(req) {
creating data internally if i refer bulkCreate and bulkUpdate and find api all this API need an internal-access-token . Still i will confirm with @VISHNUDAS-tunerlabs  and make the changes if require

2024-08-01 15:48 UTC, aks30 requested changes
Reviewed on 1 Aug 9:30 PM

2024-08-01 15:48 UTC, aks30 commented on src/models/userRoleExtension.js
> +		userType: {
Remove this key

2024-08-01 15:48 UTC, aks30 commented on src/module/entities/helper.js
> +						message: CONSTANTS.apiResponses.ENTITYTYPE_NOT_FOUND,
@MallanagoudaB Change it to ENTITY_NOT_FOUND

2024-08-01 15:48 UTC, aks30 commented on src/models/userRoleExtension.js
> +				entityType: { type: String, index: true },
@MallanagoudaB Remove this index.

2024-08-01 16:05 UTC, merged